version: "3.9"
services:
  vintagestory-server:
    build:
      context: .
      args:
        - vs_branch=stable
        - vs_version=1.18.6
    image: vintagestory-docker
    container_name: vintagestory-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - /appdata/vintagestory:/gamedata
    ports:
      - 42420:42420
    environment:
      VS_GAMEDATA: /gamedata
